ccflags-y += -ffreestanding -mfpu=neon -mfloat-abi=softfp -O3

math-objs += w_pow.o e_pow.o s_rint.o s_copysign.o s_scalbn.o s_fabs.o e_sqrt.o w_sqrt.o k_tan.o \
s_tan.o k_rem_pio2.o e_rem_pio2.o s_floor.o k_cos.o s_cos.o k_sin.o s_sin.o s_atan.o

obj-y += math.o
